(function(root){
'use strict';const api={
escape:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),
safeUrl(v){try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}},
dayKey(d){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');},
resolve(registry,search){const p=new URLSearchParams(search),id=p.get('client')||registry.defaultClient;if(!Object.hasOwn(registry.clients,id))throw new Error('Unknown client');const c=registry.clients[id];const requested=p.get('lang');return {config:c,lang:c.languages.includes(requested)?requested:c.defaultLanguage};},
link(path,client,lang){const [base,hash]=path.split('#');const u=new URL(base||'index.html','http://local/');u.searchParams.set('client',client);u.searchParams.set('lang',lang);return `${u.pathname.slice(1)}${u.search}${hash?'#'+hash:''}`;},
futureDays(cal,now=new Date(),timeZone='Europe/Amsterdam'){const parts=new Intl.DateTimeFormat('en',{timeZone,year:'numeric',month:'numeric',day:'numeric'}).formatToParts(now);const get=type=>Number(parts.find(p=>p.type===type).value);const days=[];for(let i=1;i<=28&&days.length<10;i++){const d=new Date(Date.UTC(get('year'),get('month')-1,get('day')+i,12));if(cal.workingDays.includes(d.getUTCDay()))days.push(d);}return days;},
demoSlots(config,date){const hours=config.hours?.find(h=>h.days.includes(date.getUTCDay()));if(hours?.closed)return [];return config.calendar.exampleSlots.filter(time=>!hours||(time>=hours.open&&time<hours.close));},
reviewCopy(review,target){const original=typeof review.originalText==='string'?{text:review.originalText,languageCode:review.originalLanguage}:review.originalText||{},display=typeof review.text==='string'?{text:review.text,languageCode:review.language||review.languageCode}:review.text||{};const matches=code=>String(code||'').toLowerCase().split('-')[0]===target.split('-')[0].toLowerCase();if(original.text&&matches(original.languageCode))return {text:original.text,originalText:original.text,languageCode:original.languageCode,sourceLanguage:original.languageCode,translated:false,translationAvailable:true};const text=display.text||original.text||'';return {text,originalText:original.text||text,languageCode:display.languageCode||original.languageCode||'',sourceLanguage:original.languageCode||display.languageCode||'',translated:!!original.text&&text!==original.text,translationAvailable:matches(display.languageCode)};},
relativeTime(text,target){const value=String(text||''),edited=value.startsWith('Bewerkt:'),match=value.replace(/^Bewerkt:\s*/,'').match(/^(\d+) (jaar|jaren|maand|maanden|week|weken|dag|dagen|uur) geleden$/);if(!match)return text||'';const units={jaar:'year',jaren:'year',maand:'month',maanden:'month',week:'week',weken:'week',dag:'day',dagen:'day',uur:'hour'},prefix=edited?({nl:'Bewerkt: ',en:'Edited: ',es:'Editado: ',ca:'Editat: '}[target]||''):'';return prefix+new Intl.RelativeTimeFormat(api.locale(target),{numeric:'always'}).format(-Number(match[1]),units[match[2]]);},
snapshotData(config,target){const snapshot=config.google?.snapshot;if(!snapshot||!/^\d{4}-\d{2}-\d{2}$/.test(snapshot.checked||'')||(snapshot.clientId&&snapshot.clientId!==config.id))return null;return {...snapshot,reviews:(snapshot.reviews||[]).map(review=>{const original=typeof review.originalText==='string'?review.originalText:review.text,originalLanguage=review.originalLanguage||review.language||'en',translation=review.translations?.[target];return {...review,originalText:original,originalLanguage,text:translation||original,language:translation?target:originalLanguage,relativeTime:review.relativeTimes?.[target]||api.relativeTime(review.relativeTime,target),translationSource:translation?'concept':undefined};})};},
mapEmbed(config){const u=new URL('https://www.google.com/maps');u.searchParams.set('q',[config.name,config.business.address].filter(Boolean).join(' '));u.searchParams.set('output','embed');u.searchParams.set('z','16');const p=config.business.coordinates;if(p&&Number.isFinite(p.lat)&&Number.isFinite(p.lng))u.searchParams.set('ll',`${p.lat},${p.lng}`);return u.href;},
whatsappUrl(number,message){const n=String(number).replace(/[+\s()-]/g,'');return /^[1-9]\d{7,14}$/.test(n)?`https://wa.me/${n}?text=${encodeURIComponent(message)}`:'';},
calendarUrl(v){try{const u=new URL(v);return u.protocol==='https:'&&['calendar.google.com','calendar.app.google'].includes(u.hostname)?u.href:'';}catch{return '';}},
brandIcon(config){const id=config.id||'',sector=config.sector||'',type=config.brandIcon||({ayden:'salon',bloom:'salon',dental:'dental',lumen:'dental',accounting:'accounting',northline:'accounting',moving:'moving',brightmove:'moving',fogon:'restaurant',brasa:'restaurant',ff:'automotive'}[id])||(sector.includes('hair')?'salon':sector.includes('dent')?'dental':sector.includes('account')?'accounting':sector.includes('mov')?'moving':sector.includes('restaurant')?'restaurant':'salon');const paths={salon:'<circle cx="8" cy="10" r="4"/><circle cx="8" cy="26" r="4"/><path d="m11 13 21 19M11 23 30 4M18 18l-2-2"/>',dental:'<path d="M14 5C7 1 3 6 6 15l3 10c2 7 5 9 7 5l2-9 2 9c2 4 5 2 7-5l3-10c3-9-1-14-8-10-3 2-5 2-8 0Z"/>',accounting:'<path d="M7 3h22v30H7Z M12 9h12M12 14h6M12 28v-5M18 28V18M24 28v-8"/>',moving:'<path d="m4 15 14-11 14 11M7 14v17h22V14M13 31V19h10v12"/><path d="m5 26 5-3 5 3v7H5ZM5 26l5 3 5-3M10 29v4"/>',restaurant:'<path d="M19 3c2 8-3 10-4 15-2-3-2-5-1-8-7 5-9 10-7 16 2 7 12 9 18 4 7-6 5-15-1-22 1 8-2 10-4 12 1-7 1-10-1-17Z"/>',automotive:'<path d="M27 4a8 8 0 0 0-10 11L5 27a3 3 0 0 0 4 4l12-12A8 8 0 0 0 32 9l-6 5-4-4Z"/>'};return `<svg class="brand-symbol" viewBox="0 0 36 36" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[type]||paths.salon}</svg>`;},
locale:lang=>({nl:'nl-NL',en:'en-GB',es:'es-ES',ca:'ca-ES'}[lang]||'en-GB')};
if(typeof module!=='undefined')module.exports=api;root.SiteCore=api;
})(typeof window==='undefined'?globalThis:window);
