(function(root){
 'use strict';
 const rows={notice:['Onafhankelijk websiteconcept van Ocimatik','Independent website concept by Ocimatik'],skip:['Naar inhoud','Skip to content'],information:['Informatie','Information'],location:['Locatie & ervaringen','Location & reviews'],contact:['Contact','Contact'],plan:['Plan een afspraak','Plan an appointment'],explore:['Bekijk de mogelijkheden','Explore the options'],brandLabel:['Websiteconcept','Website concept'],learn:['Bekijk tijden','View times'],localTitle:['Dichtbij.\nGoed bereikbaar.','Nearby.\nEasy to reach.'],mapTitle:['Locatie op Google Maps','Location on Google Maps'],directions:['Bekijk de route','View directions'],mapPending:['Een adres dichtbij.','An address nearby.'],mapPendingText:['De locatie verschijnt zodra een bedrijf aan dit concept is gekoppeld.','The location appears once a business is connected to this concept.'],reviewTitle:['Ervaringen op Google','Experiences on Google'],reviewPending:['De eigen Google-beoordelingen en foto’s verschijnen na aansluiting van het bedrijf.','The business’s own Google reviews and photos appear once connected.'],reviews:['beoordelingen','reviews'],reviewsLink:['Bekijk op Google Maps','View on Google Maps'],reviewLoading:['Beoordelingen laden…','Loading reviews…'],reviewError:['Beoordelingen zijn nu niet beschikbaar.','Reviews are unavailable right now.'],reviewEmpty:['Google heeft geen beoordelingsteksten beschikbaar gesteld.','Google did not provide review text.'],reviewOrder:['Selectie door Google, op relevantie.','Selected by Google, ordered by relevance.'],previous:['Vorige','Previous'],next:['Volgende','Next'],play:['Automatisch afspelen','Play automatically'],pause:['Pauzeren','Pause'],translated:['Vertaald door Google','Translated by Google'],original:['Originele beoordeling','Original review'],read:['Lees op Google Maps','Read on Google Maps'],contactEyebrow:['JE VOLGENDE STAP','YOUR NEXT STEP'],contactIntro:['Kies een afspraak of stuur een algemene vraag.','Choose an appointment or send a general enquiry.'],call:['Bel het bedrijf','Call the business'],hours:['Openingstijden','Opening hours'],closed:['Gesloten','Closed'],whatsapp:['WhatsApp','WhatsApp'],whatsappMessage:['Hallo, ik wil graag meer informatie.','Hello, I would like more information.'],footer:['Onafhankelijk websiteconcept door Ocimatik.','Independent website concept by Ocimatik.'],privacy:['Privacy','Privacy'],googleTerms:['Google Maps voorwaarden','Google Maps terms'],photos:['Foto’s via Google Maps','Photos via Google Maps']};
 rows.translatedConcept=['Vertaling voor dit concept','Translation for this concept'];
 function render({client:c,lang,visual='',logo='',icons=()=>''}){
  const C=root.SiteCore,h=C.escape,t=key=>c.ui?.[key]?.[lang]||rows[key]?.[lang==='nl'?0:1]||key,l=value=>typeof value==='string'?value:value?.[lang]||'';
  document.documentElement.lang=lang;document.title=c.name+' · '+t('brandLabel');document.getElementById('skip').textContent=t('skip');
  const booking=service=>'../../booking.html?'+new URLSearchParams({client:c.id,lang,...(service?{service}:{} )});
  const plan=(cls='button',service)=>`<a class="${cls}" href="${h(booking(service))}">${h(t('plan'))} <span aria-hidden="true">↗</span></a>`;
  const external=(url,label,cls='text-link')=>C.safeUrl(url)?`<a class="${cls}" href="${h(C.safeUrl(url))}" target="_blank" rel="noopener noreferrer">${h(label)} ↗</a>`:'';
  const brand=`<a class="brand" href="index.html?lang=${lang}">${C.brandIcon(c)}<span>${h(c.shortName)}<small>${h(t('brandLabel'))}</small></span></a>`;
  const call=c.business.phone?`<a class="button light" href="tel:${h(c.business.phone)}">${h(t('call'))} ↗</a>`:'';
  document.getElementById('header').innerHTML=`<div class="notice">${h(t('notice'))}</div><header class="container header-inner">${brand}<nav class="nav" aria-label="${h(t('information'))}"><a href="#information">${h(t('information'))}</a><a href="#location">${h(t('location'))}</a><a href="#contact">${h(t('contact'))}</a></nav><div class="header-actions"><div class="langs">${c.languages.map(code=>`<a href="index.html?lang=${code}" lang="${code}" class="${code===lang?'active':''}" aria-current="${code===lang?'true':'false'}">${code.toUpperCase()}</a>`).join('')}</div>${plan('button small')}</div></header>`;
  const hasMap=!!c.business.address&&(!!c.google.placeId||!!c.business.coordinates);
  const map=hasMap?`<div class="map"><iframe title="${h(t('mapTitle'))}" src="${h(C.mapEmbed(c))}" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe><div class="map-caption"><strong>${h(c.name)}</strong><p>${h(c.business.address)}</p>${external(c.business.mapsUrl,t('directions'))}</div></div>`:`<div class="map map-concept"><svg viewBox="0 0 60 72" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M30 67S7 42 7 28a23 23 0 1 1 46 0C53 42 30 67 30 67Z"/><circle cx="30" cy="28" r="9"/></svg><h3>${h(t('mapPending'))}</h3><p>${h(t('mapPendingText'))}</p></div>`;
  const hours=c.hours?.length?`<h3>${h(t('hours'))}</h3><div class="hours">${c.hours.map(item=>`<div><span>${item.days.map(day=>new Intl.DateTimeFormat(C.locale(lang),{weekday:'short'}).format(new Date(2026,0,4+day))).join(', ')}</span><span>${item.closed?h(t('closed')):h(item.open)+'–'+h(item.close)}</span></div>`).join('')}</div>`:'';
  const whatsapp=c.whatsapp.enabled?C.whatsappUrl(c.whatsapp.number,t('whatsappMessage')):'';
  document.getElementById('main').innerHTML=`<section class="hero"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">${h(l(c.copy.eyebrow))}</p><h1>${h(l(c.copy.heroTitle)).replace(/\n/g,'<br>')}</h1><p class="hero-intro">${h(l(c.copy.heroIntro))}</p><div class="actions">${plan()}<a class="button outline" href="#information">${h(t('explore'))} ↓</a></div></div>${visual}</div></section><section class="section" id="information"><div class="container"><div class="section-head"><div><p class="eyebrow">${h(t('information'))}</p><h2>${h(l(c.copy.serviceTitle)).replace(/\n/g,'<br>')}</h2></div><p>${h(l(c.copy.serviceIntro))}</p></div><div class="service-grid services-compact">${c.services.map(service=>`<article class="service-card"><div class="service-icon">${icons(service.icon)}</div><div class="service-copy"><h3>${h(l(service.title))}</h3><p>${h(l(service.description))}</p></div><a class="text-link" href="${h(booking(service.id))}">${h(t('learn'))} ↗</a></article>`).join('')}</div></div></section><section class="section" id="location"><div class="container"><div class="section-head"><div><p class="eyebrow">Google Maps</p><h2>${h(t('localTitle')).replace(/\n/g,'<br>')}</h2></div></div><div class="location-grid">${map}<div class="reviews" id="reviews"><img src="../../assets/google-maps.svg" alt="Google Maps" width="110" height="20"><h3>${h(t('reviewTitle'))}</h3><p>${h(t(c.google.enabled?'reviewLoading':'reviewPending'))}</p>${external(c.business.mapsUrl,t('reviewsLink'))}</div></div><div class="photo-gallery" id="photos" hidden></div></div></section><section class="section contact-section" id="contact"><div class="container contact-grid"><div><p class="eyebrow">${h(t('contactEyebrow'))}</p><h2>${h(l(c.copy.contactTitle)).replace(/\n/g,'<br>')}</h2><p>${h(t('contactIntro'))}</p><div class="actions">${plan('button light')}${call}${whatsapp?external(whatsapp,t('whatsapp'),'button light'):''}</div>${c.business.address?`<p>${h(c.business.address)}</p>`:''}${hours}</div><div class="contact-form-container"><div data-contact-widget></div></div></div></section>`;
  document.getElementById('footer').innerHTML=`<div class="container footer-inner">${brand}<p>${h(t('footer'))}</p><div class="footer-links"><a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">${h(t('privacy'))}</a><a href="https://cloud.google.com/maps-platform/terms" target="_blank" rel="noopener noreferrer">${h(t('googleTerms'))}</a></div></div>`;
  root.ContactWidget?.mountAll({client:c,lang});
  function carousel(type,slides){return `<div data-carousel role="region" aria-label="${h(t(type==='photo'?'photos':'reviewTitle'))}"><div class="carousel-track" data-carousel-track tabindex="0">${slides}</div><div class="carousel-footer"><span class="carousel-position" data-carousel-progress></span><button class="carousel-autoplay" data-carousel-toggle type="button" aria-pressed="false">${h(t('play'))}</button><div class="carousel-arrows"><button data-carousel-prev type="button" aria-label="${h(t('previous'))}">←</button><button data-carousel-next type="button" aria-label="${h(t('next'))}">→</button></div></div></div>`;}
  function review(item){const copy=C.reviewCopy(item,lang),name=item.authorName||item.author?.displayName||'Google Maps',photo=item.profilePhotoUrl||item.author?.photoUri,uri=item.authorUri||item.author?.uri,stars=Math.round(Math.max(0,Math.min(5,item.rating||0)));return `<article class="review-card"><div class="review-author">${C.safeUrl(photo)?`<img src="${h(C.safeUrl(photo))}" alt="${h(name)}" width="44" height="44">`:''}<div>${external(uri,name)||`<strong>${h(name)}</strong>`}<small>${h(item.relativeTime||item.relativeDate||'')}</small></div></div><p class="review-stars" aria-label="${h(item.rating)} / 5">${'★'.repeat(stars)}${'☆'.repeat(5-stars)}</p><p class="review-text" lang="${h(copy.languageCode||lang)}">${h(copy.text)}</p>${copy.translated?`<details><summary>${h(t(item.translationSource==='concept'?'translatedConcept':'translated'))} · ${h(t('original'))}</summary><p lang="${h(copy.sourceLanguage)}">${h(copy.originalText)}</p></details>`:''}${external(item.googleMapsUri||c.business.mapsUrl,t('read'))}</article>`;}
  const snapshot=C.snapshotData(c,lang);
  function showReviews(data,archived=false){const box=document.getElementById('reviews');const checked=archived?new Intl.DateTimeFormat(C.locale(lang),{dateStyle:'medium'}).format(new Date(data.checked+'T12:00:00Z')):'';box.innerHTML=`<img src="../../assets/google-maps.svg" alt="Google Maps" width="110" height="20">${data.total?`<h3>${h(new Intl.NumberFormat(C.locale(lang),{minimumFractionDigits:1}).format(data.rating))} / 5</h3><p>${h(data.total)} ${h(t('reviews'))}</p>`:''}${data.reviews?.length?carousel('review',data.reviews.map(review).join('')):`<p>${h(t('reviewEmpty'))}</p>`}<p class="integration-note">${archived?`Google Maps · ${h(checked)}`:h(t('reviewOrder'))}</p>`;}
  function showPhotos(data){if(!data?.photos?.length)return;const photos=document.getElementById('photos');photos.hidden=false;photos.innerHTML=carousel('photo',data.photos.map(photo=>`<figure class="photo-slide"><img src="${h(C.safeUrl(photo.url))}" alt="${h(t('photos'))}" loading="lazy" width="900" height="600"><figcaption>${(photo.authorAttributions||[]).map(author=>external(author.uri,author.displayName)).join(' · ')} ${external(photo.googleMapsUri,'Google Maps')}</figcaption></figure>`).join(''))+`<div class="google-credit"><img src="../../assets/google-maps.svg" alt="Google Maps" width="98" height="18"></div>`;}
  let mounted=[];
  function mountCarousels(){mounted.forEach(item=>item.destroy());mounted=Array.from(document.querySelectorAll('[data-carousel]')).map(element=>root.SalonCarousel.mount(element,{playLabel:t('play'),pauseLabel:t('pause')}));}
  root.addEventListener('pagehide',()=>mounted.forEach(item=>item.destroy()),{once:true});
  if(snapshot?.reviews?.length){showReviews(snapshot,true);showPhotos(snapshot);mountCarousels();}
  async function loadGoogle(){
   if(!c.google.enabled||(!c.google.placeId&&!c.google.resolvePlaceId))return;
   const request=async path=>{const url=new URL(path,location.origin);if(url.origin!==location.origin)throw new Error('Origin');url.search=new URLSearchParams({client:c.id,lang});const response=await fetch(url,{credentials:'same-origin',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('Unavailable');return response.json();};
   const results=await Promise.allSettled([request(c.google.reviewsEndpoint||'/api/google-reviews'),c.google.photosEnabled?request(c.google.endpoint||'/api/place'):Promise.resolve(null)]),box=document.getElementById('reviews');
   if(results[0].status==='fulfilled')showReviews(results[0].value);else if(!snapshot?.reviews?.length)box.innerHTML=`<img src="../../assets/google-maps.svg" alt="Google Maps" width="110" height="20"><h3>${h(t('reviewTitle'))}</h3><p>${h(t('reviewError'))}</p>${external(c.business.mapsUrl,t('reviewsLink'))}`;
   if(results[1].status==='fulfilled')showPhotos(results[1].value);
   mountCarousels();
  }
  loadGoogle();
 }
 root.SectorSite={render,rows};
})(typeof window==='undefined'?globalThis:window);
