(function(root){
 'use strict';
 const rows={notice:['Onafhankelijk websiteconcept van Ocimatik','Independent website concept by Ocimatik'],skip:['Naar inhoud','Skip to content'],information:['Informatie','Information'],location:['Locatie & ervaringen','Location & reviews'],contact:['Contact','Contact'],plan:['Plan een afspraak','Plan an appointment'],explore:['Bekijk de mogelijkheden','Explore the options'],brandLabel:['Websiteconcept','Website concept'],learn:['Bekijk tijden','View times'],localTitle:['Dichtbij.\nGoed bereikbaar.','Nearby.\nEasy to reach.'],mapTitle:['Locatie op Google Maps','Location on Google Maps'],directions:['Bekijk de route','View directions'],mapPending:['Een adres dichtbij.','An address nearby.'],mapPendingText:['De locatie verschijnt zodra een bedrijf aan dit concept is gekoppeld.','The location appears once a business is connected to this concept.'],reviewTitle:['Ervaringen op Google','Experiences on Google'],reviewPending:['De eigen Google-beoordelingen en foto’s verschijnen na aansluiting van het bedrijf.','The business’s own Google reviews and photos appear once connected.'],reviews:['beoordelingen','reviews'],reviewsLink:['Bekijk op Google Maps','View on Google Maps'],reviewLoading:['Beoordelingen laden…','Loading reviews…'],reviewError:['Beoordelingen zijn nu niet beschikbaar.','Reviews are unavailable right now.'],reviewEmpty:['Google heeft geen beoordelingsteksten beschikbaar gesteld.','Google did not provide review text.'],reviewOrder:['Selectie door Google, op relevantie.','Selected by Google, ordered by relevance.'],previous:['Vorige','Previous'],next:['Volgende','Next'],play:['Automatisch afspelen','Play automatically'],pause:['Pauzeren','Pause'],translated:['Vertaald door Google','Translated by Google'],original:['Originele beoordeling','Original review'],read:['Lees op Google Maps','Read on Google Maps'],contactEyebrow:['JE VOLGENDE STAP','YOUR NEXT STEP'],contactIntro:['Kies een afspraak of stuur een algemene vraag.','Choose an appointment or send a general enquiry.'],call:['Bel het bedrijf','Call the business'],hours:['Openingstijden','Opening hours'],closed:['Gesloten','Closed'],whatsapp:['WhatsApp','WhatsApp'],whatsappMessage:['Hallo, ik wil graag meer informatie.','Hello, I would like more information.'],footer:['Onafhankelijk websiteconcept door Ocimatik.','Independent website concept by Ocimatik.'],privacy:['Privacy','Privacy'],googleTerms:['Google Maps voorwaarden','Google Maps terms'],photos:['Foto’s via Google Maps','Photos via Google Maps']};
 rows.translatedConcept=['Vertaling','Translation'];
 function render({client:c,lang,visual='',logo='',icons=()=>'',onPlace}){
  const C=root.SiteCore,h=C.escape,t=key=>c.ui?.[key]?.[lang]||rows[key]?.[lang==='nl'?0:1]||key,l=value=>typeof value==='string'?value:value?.[lang]||'';
  const sector=String(c.sector||''),sectorClass=sector.includes('dent')?'dental':sector.includes('account')?'accounting':sector.includes('mov')?'moving':sector.includes('restaurant')?'restaurant':'general';
  document.body?.classList?.add('sector-'+sectorClass);document.documentElement.dataset&&(document.documentElement.dataset.sector=sectorClass);
  document.documentElement.lang=lang;document.title=c.name+' · '+C.brandDescriptor(c,lang);document.getElementById('skip').textContent=t('skip');
  const booking=service=>'../../booking.html?'+new URLSearchParams({client:c.id,lang,...(service?{service}:{} )});
  const home=language=>'index.html?'+new URLSearchParams({...(c.pitch?{client:c.id}:{}),lang:language});
  const plan=(cls='button',service)=>`<a class="${cls}" href="${h(booking(service))}">${h(t('plan'))} <span aria-hidden="true">↗</span></a>`;
  const external=(url,label,cls='text-link')=>C.safeUrl(url)?`<a class="${cls}" href="${h(C.safeUrl(url))}" target="_blank" rel="noopener noreferrer">${h(label)} ↗</a>`:'';
  const brand=`<a class="brand" href="${h(home(lang))}" aria-label="${h(c.name)}" title="${h(c.name)}">${C.brandIcon(c)}<span>${h(c.shortName)}<small class="brand-descriptor">${h(C.brandDescriptor(c,lang))}</small></span></a>`;
  const call=c.business.phone?`<a class="button light" href="tel:${h(c.business.phone)}">${h(t('call'))} ↗</a>`:'';
  document.getElementById('header').innerHTML=`<header class="container header-inner">${brand}<nav class="nav" aria-label="${h(t('information'))}"><a href="#information">${h(t('information'))}</a><a href="#location">${h(t('location'))}</a><a href="#contact">${h(t('contact'))}</a></nav><div class="header-actions"><div class="langs" role="group" aria-label="${h(lang==='nl'?'Taal':'Language')}">${C.languageOrder(c.languages).map(code=>`<a href="${h(home(code))}" lang="${code}" class="${code===lang?'active':''}" aria-current="${code===lang?'true':'false'}" aria-label="${h(C.languageName(code))}">${C.languageContent(code)}</a>`).join('')}</div>${plan('button small')}</div></header>`;
  const hasMap=!!c.business.address&&(!!c.google.placeId||!!c.business.coordinates);
  const map=hasMap?`<div class="map"><iframe title="${h(t('mapTitle'))}" src="${h(C.mapEmbed(c))}" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe><div class="map-caption"><strong>${h(c.name)}</strong><p>${h(c.business.address)}</p>${external(c.business.mapsUrl,t('directions'))}</div></div>`:`<div class="map map-concept"><svg viewBox="0 0 60 72" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M30 67S7 42 7 28a23 23 0 1 1 46 0C53 42 30 67 30 67Z"/><circle cx="30" cy="28" r="9"/></svg><h3>${h(t('mapPending'))}</h3><p>${h(t('mapPendingText'))}</p></div>`;
  const hours=c.hours?.length?`<h3>${h(t('hours'))}</h3><div class="hours">${c.hours.map(item=>`<div><span>${item.days.map(day=>new Intl.DateTimeFormat(C.locale(lang),{weekday:'short'}).format(new Date(2026,0,4+day))).join(', ')}</span><span>${item.closed?h(t('closed')):h(item.open)+'–'+h(item.close)}</span></div>`).join('')}</div>`:'';
  const whatsapp=c.whatsapp.enabled?C.whatsappUrl(c.whatsapp.number,t('whatsappMessage')):'';
  const labels={nl:{dental:['Je bezoek','Locatie','Contact'],accounting:['Diensten','Ervaringen','Contact'],moving:['Verhuishulp','Locatie','Contact'],restaurant:['De kaart','Ervaringen','Contact']},en:{dental:['Your visit','Location','Contact'],accounting:['Services','Experiences','Contact'],moving:['Moving help','Location','Contact'],restaurant:['The menu','Experiences','Contact']}};
  const header=document.getElementById('header');header.dataset&&(header.dataset.theme=sectorClass);
  header.querySelector?.('.header-inner')?.classList.add('header-'+sectorClass);
  header.querySelectorAll?.('.nav>a').forEach((anchor,index)=>{if(labels[lang]?.[sectorClass]?.[index])anchor.textContent=labels[lang][sectorClass][index];});
  const explore={nl:{dental:'Over je bezoek',accounting:'Bekijk de diensten',restaurant:'Bekijk de kaart'},en:{dental:'About your visit',accounting:'Explore the services',restaurant:'Explore the menu'}}[lang]?.[sectorClass]||t('explore');
  const intro=`<div class="hero-copy"><p class="eyebrow">${h(l(c.copy.eyebrow))}</p><h1>${h(l(c.copy.heroTitle)).replace(/\n/g,'<br>')}</h1><p class="hero-intro">${h(l(c.copy.heroIntro))}</p><div class="actions">${plan()}${sectorClass==='moving'?'':`<a class="button outline" href="#information">${h(explore)} ↓</a>`}</div></div>`;
  const serviceLinks=(className)=>`<nav class="${className}" aria-label="${h(t('information'))}">${c.services.slice(0,3).map(service=>`<a href="${h(sectorClass==='restaurant'?'#information':service.bookingEligible===false?'#contact':booking(service.id))}"><span>${h(l(service.title))}</span><span aria-hidden="true">↗</span></a>`).join('')}</nav>`;
  const routeCopy=lang==='nl'?{title:'Waar gaat jouw verhuizing naartoe?',from:'Van · plaats of postcode',to:'Naar · plaats of postcode',date:'Gewenste verhuisdatum',start:'Maak je verhuisplan'}:{title:'Where is your move taking you?',from:'From · city or postcode',to:'To · city or postcode',date:'Preferred moving date',start:'Start your moving plan'};
  const routeStarter=`<div class="route-starter" role="group" aria-labelledby="routeStarterTitle"><h2 id="routeStarterTitle">${h(routeCopy.title)}</h2><div class="route-starter-fields"><div><label for="routeFrom">${h(routeCopy.from)}</label><input id="routeFrom" name="routeFrom" maxlength="90" autocomplete="off"></div><span class="route-connector" aria-hidden="true">→</span><div><label for="routeTo">${h(routeCopy.to)}</label><input id="routeTo" name="routeTo" maxlength="90" autocomplete="off"></div><div><label for="routeDate">${h(routeCopy.date)}</label><input id="routeDate" name="routeDate" type="date"></div><button class="button route-start-button" type="button">${h(routeCopy.start)} <span aria-hidden="true">↗</span></button></div></div>`;
  const heroMarkup=sectorClass==='dental'?`<section class="hero hero--practice"><div class="container hero-grid">${intro}${visual}</div><div class="container">${serviceLinks('practice-links')}</div></section>`:sectorClass==='accounting'?`<section class="hero hero--ledger"><div class="container hero-grid">${intro}${visual}${serviceLinks('ledger-links')}</div></section>`:sectorClass==='moving'?`<section class="hero hero--route"><div class="container hero-grid">${intro}${visual}${routeStarter}</div></section>`:sectorClass==='restaurant'?`<section class="hero hero--supper"><div class="container hero-grid">${intro}${visual}</div><div class="container">${serviceLinks('supper-menu-links')}</div></section>`:`<section class="hero"><div class="container hero-grid">${intro}${visual}</div></section>`;
  document.getElementById('main').innerHTML=`${heroMarkup}<section class="section" id="information"><div class="container"><div class="section-head"><div><p class="eyebrow">${h(t('information'))}</p><h2>${h(l(c.copy.serviceTitle)).replace(/\n/g,'<br>')}</h2></div><p>${h(l(c.copy.serviceIntro))}</p></div><div class="service-grid services-compact">${c.services.map(service=>`<article class="service-card"><div class="service-icon">${icons(service.icon)}</div><div class="service-copy"><h3>${h(l(service.title))}</h3><p>${h(l(service.description))}</p></div><a class="text-link" href="${h(service.bookingEligible===false?'#contact':booking(service.id))}">${h(t(service.bookingEligible===false?'contact':'learn'))} ↗</a></article>`).join('')}</div></div></section><section class="section" id="location"><div class="container"><div class="section-head"><div><p class="eyebrow">Google Maps</p><h2>${h(t('localTitle')).replace(/\n/g,'<br>')}</h2></div></div><div class="location-grid">${map}<div class="reviews" id="reviews"><img src="../../assets/google-maps.svg" alt="Google Maps" width="110" height="20"><h3>${h(t('reviewTitle'))}</h3><p>${h(t(c.google.enabled?'reviewLoading':'reviewPending'))}</p>${external(c.business.mapsUrl,t('reviewsLink'))}</div></div><div class="photo-gallery" id="photos" hidden></div></div></section><section class="section contact-section" id="contact"><div class="container contact-grid"><div><p class="eyebrow">${h(t('contactEyebrow'))}</p><h2>${h(l(c.copy.contactTitle)).replace(/\n/g,'<br>')}</h2><p>${h(t('contactIntro'))}</p><div class="actions">${plan('button light')}${call}${whatsapp?external(whatsapp,t('whatsapp'),'button light'):''}</div>${c.business.address?`<p>${h(c.business.address)}</p>`:''}${hours}</div><div class="contact-form-container"><div data-contact-widget></div></div></div></section>`;
  document.getElementById('footer').innerHTML=`<div class="container footer-inner">${brand}<p>${h(c.name)} · ${h(c.business.city||'')}</p><div class="footer-links"><a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">${h(t('privacy'))}</a><a href="https://cloud.google.com/maps-platform/terms" target="_blank" rel="noopener noreferrer">${h(t('googleTerms'))}</a></div></div>`;
  root.ContactWidget?.mountAll({client:c,lang});
  if(sectorClass==='moving'){
   const date=document.getElementById('routeDate'),start=document.querySelector?.('.route-start-button');
   if(date)date.min=C.futureDays({workingDays:[0,1,2,3,4,5,6]},new Date(),c.timeZone)[0].toISOString().slice(0,10);
   start?.addEventListener('click',()=>{
    if(date?.value&&!date.reportValidity())return;
    const form=document.querySelector('[data-contact-widget] form');if(!form)return;
    for(const [source,target]of [['routeFrom','movingFrom'],['routeTo','movingTo'],['routeDate','movingDate']]){
     const input=document.getElementById(source),field=form.elements.namedItem(target);if(field&&input)field.value=String(input.value||'').trim().slice(0,90);
    }
    document.getElementById('contact').scrollIntoView({behavior:root.matchMedia?.('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});
    form.elements.namedItem('name')?.focus({preventScroll:true});
   });
  }
  function carousel(type,slides){return `<div data-carousel role="region" aria-label="${h(t(type==='photo'?'photos':'reviewTitle'))}"><div class="carousel-track" data-carousel-track tabindex="0">${slides}</div><div class="carousel-footer"><span class="carousel-position" data-carousel-progress></span><button class="carousel-autoplay" data-carousel-toggle type="button" aria-pressed="false">${h(t('play'))}</button><div class="carousel-arrows"><button data-carousel-prev type="button" aria-label="${h(t('previous'))}">←</button><button data-carousel-next type="button" aria-label="${h(t('next'))}">→</button></div></div></div>`;}
  function review(item){
   const copy=C.reviewCopy(item,lang),name=item.authorName||item.author?.displayName||'Google Maps',photo=item.profilePhotoUrl||item.author?.photoUri,uri=item.authorUri||item.author?.uri,stars=Math.round(Math.max(0,Math.min(5,item.rating||0)));
   const avatar=C.safeUrl(photo)?`<img class="review-avatar" src="${h(C.safeUrl(photo))}" alt="${h(name)}" width="56" height="56" loading="lazy">`:`<span class="review-avatar review-initial" aria-hidden="true">${h(name.slice(0,1))}</span>`;
   return `<article class="review-card" data-review-card="google"><div class="review-author">${avatar}<div>${external(uri,name,'review-author-link')||`<strong class="review-author-link">${h(name)}</strong>`}<span class="review-date">${h(item.relativeTime||item.relativeDate||'')}</span></div></div><div class="review-score"><span class="review-stars" role="img" aria-label="${h(item.rating)} ${lang==='nl'?'van':'out of'} 5"><span aria-hidden="true">${'★'.repeat(stars)}<span class="review-stars-empty">${'☆'.repeat(5-stars)}</span></span></span><span class="review-score-value" aria-hidden="true">${h(item.rating)} / 5</span></div><blockquote class="review-text" lang="${h(copy.languageCode||lang)}">${h(copy.text)}</blockquote>${copy.translated?`<details class="original-review"><summary>${h(t(item.translationSource==='concept'?'translatedConcept':'translated'))} · ${h(t('original'))}</summary><p lang="${h(copy.sourceLanguage)}">${h(copy.originalText)}</p></details>`:''}<footer class="review-source"><img class="review-google" src="../../assets/google-maps.svg" alt="Google Maps" width="98" height="18">${external(item.googleMapsUri||c.business.mapsUrl,t('read'))}</footer></article>`;
  }
  const snapshot=C.snapshotData(c,lang);
  function showReviews(data,archived=false){const box=document.getElementById('reviews');const checked=archived?new Intl.DateTimeFormat(C.locale(lang),{dateStyle:'medium'}).format(new Date(data.checked+'T12:00:00Z')):'';box.innerHTML=`<div class="review-summary"><img src="../../assets/google-maps.svg" alt="Google Maps" width="110" height="20">${data.total?`<div><h3>${h(new Intl.NumberFormat(C.locale(lang),{minimumFractionDigits:1}).format(data.rating))} <span>/ 5</span></h3><p>${h(data.total)} ${h(t('reviews'))}</p></div>`:''}</div>${data.reviews?.length?carousel('review',data.reviews.map(review).join('')):`<p>${h(t('reviewEmpty'))}</p>`}<p class="integration-note">${archived?`Google Maps · ${h(checked)}`:h(t('reviewOrder'))}</p>`;}
  function showPhotos(data){const unique=C.uniquePhotos(data?.photos,[],location.href);if(!unique.length)return;const photos=document.getElementById('photos');photos.hidden=false;photos.innerHTML=`<div class="photo-grid" data-photo-count="${unique.length}">${unique.map(photo=>`<figure class="photo-slide"><img src="${h(C.safeUrl(photo.url))}" alt="${h(t('photos'))}" loading="lazy" width="900" height="600"><figcaption>${(photo.authorAttributions||[]).map(author=>external(author.uri,author.displayName)).join(' · ')} ${external(photo.googleMapsUri,'Google Maps')}</figcaption></figure>`).join('')}</div><div class="google-credit"><img src="../../assets/google-maps.svg" alt="Google Maps" width="98" height="18"></div>`;}
  let mounted=[];
  function mountCarousels(){mounted.forEach(item=>item.destroy());mounted=Array.from(document.querySelectorAll('[data-carousel]')).map(element=>root.SalonCarousel.mount(element,{playLabel:t('play'),pauseLabel:t('pause')}));}
  root.addEventListener('pagehide',()=>mounted.forEach(item=>item.destroy()),{once:true});
  if(snapshot?.reviews?.length){showReviews(snapshot,true);showPhotos(snapshot);mountCarousels();}
  async function loadGoogle(){
   if(!c.google.enabled||(!c.google.placeId&&!c.google.resolvePlaceId))return;
   const request=async path=>{const url=new URL(path,location.origin);if(url.origin!==location.origin)throw new Error('Origin');url.search=new URLSearchParams({client:c.id,lang});const response=await fetch(url,{credentials:'same-origin',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('Unavailable');return response.json();};
   const results=await Promise.allSettled([request(c.google.reviewsEndpoint||'/api/google-reviews'),c.google.photosEnabled?request(c.google.endpoint||'/api/place'):Promise.resolve(null)]),box=document.getElementById('reviews');
   if(results[0].status==='fulfilled')showReviews(results[0].value);else if(!snapshot?.reviews?.length)box.innerHTML=`<img src="../../assets/google-maps.svg" alt="Google Maps" width="110" height="20"><h3>${h(t('reviewTitle'))}</h3><p>${h(t('reviewError'))}</p>${external(c.business.mapsUrl,t('reviewsLink'))}`;
   if(results[1].status==='fulfilled'){showPhotos(results[1].value);if(results[1].value)onPlace?.(results[1].value);}
   mountCarousels();
  }
  loadGoogle();
  if(!c.concept?.fictional)root.LocaleBootstrap?.ready();
 }
 root.SectorSite={render,rows};
})(typeof window==='undefined'?globalThis:window);
