'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const registry=require('../public-client-config.js'),core=require('../core.js'),i18n=require('../i18n.js'),source=fs.readFileSync(path.join(__dirname,'../appointment.js'),'utf8');
function setup(id='bloom',mode='demo',receipt={ok:true,eventId:'provider-event'}){
 const config=structuredClone(registry.clients[id]);config.calendar.mode=mode;const nodes=new Map(),requests=[],completed=[];let temp=0;
 function node(id){if(nodes.has(id))return nodes.get(id);const events={},element={id,dataset:{},className:'',textContent:'',disabled:false,value:'2',children:[],attributes:{},setAttribute(k,v){this.attributes[k]=v;},append(child){this.children.push(child);},addEventListener(k,callback){events[k]=callback;},fire(k,extra={}){return events[k]?.({preventDefault(){},currentTarget:this,...extra});},focus(){},reportValidity:()=>true,querySelectorAll:()=>[{disabled:false}],elements:{name:{value:'Test visitor'},email:{value:'visitor@example.test'},phone:{value:''}}};let markup='';Object.defineProperty(element,'innerHTML',{get:()=>markup,set:value=>{markup=value;element.children=[];for(const match of value.matchAll(/id="([^"]+)"/g))node(match[1]);}});nodes.set(id,element);return element;}
 node('main');const document={documentElement:{dataset:{page:'booking'}},getElementById:node,createElement:()=>node('temp'+temp++),querySelector:selector=>[...nodes.values()].find(n=>selector===`[data-date="${n.dataset.date}"]`)};
 const window={Site:{config,lang:'en',t:key=>i18n.localize(config.ui?.[key],'en')||i18n.translate(key,'en'),l:value=>i18n.localize(value,'en'),h:core.escape,link:p=>'/'+core.link(p,config.id,'en')},SiteCore:core,DemoConfirmation:{complete(...args){completed.push(args);return true;}},addEventListener(){}};
 vm.runInNewContext(source,{window,document,location:{origin:'http://localhost:4174',search:'?client='+id+'&lang=en'},URL,URLSearchParams,Intl,Date,AbortController,AbortSignal,fetch:async(url,options={})=>{requests.push({url:String(url),options});if(options.method==='POST'){if(receipt instanceof Error)throw receipt;return {ok:receipt.ok!==false,json:async()=>receipt};}return {ok:true,json:async()=>({ok:true,slots:[{time:'10:00',available:true},{time:'12:00',available:false},{time:'25:70',available:true}]})};}});
 return {config,nodes,requests,completed,node};
}
const flush=()=>new Promise(resolve=>setImmediate(resolve));
async function choose(fixture){const choices=fixture.node('serviceList').children;if(choices.length)choices[0].fire('click');const date=fixture.node('dayList').children.find(n=>n.dataset.date&&!n.disabled);assert(date,'At least one open future date');date.fire('click');await flush();const slots=fixture.node('slotGrid').children;assert(slots.length);slots[0].fire('click');return date.dataset.date;}
test('monthly demo calendar excludes past and closed dates, moves between months, and routes a complete selection without network or personal data',async()=>{
 const f=setup(),firstMonth=f.node('calendarMonth').textContent;assert(f.node('monthPrevious').disabled);assert(f.node('dayList').children.some(n=>n.dataset.date&&n.disabled));f.node('monthNext').fire('click');assert.notEqual(f.node('calendarMonth').textContent,firstMonth);assert(!f.node('monthPrevious').disabled);f.node('monthPrevious').fire('click');assert.equal(f.node('calendarMonth').textContent,firstMonth);
 const date=await choose(f);assert(!f.node('bookingContinue').disabled);f.node('bookingContinue').fire('click');assert.equal(f.requests.length,0);assert.equal(f.completed.length,1);const [c,lang,summary,mode]=f.completed[0];assert.equal(c.id,'bloom');assert.equal(lang,'en');assert.equal(summary.type,'booking');assert.equal(summary.serviceId,'cut');assert.equal(summary.date,date);assert.equal(summary.time,'10:00');assert.equal(mode,'demo');assert(!('customer'in summary));
});
test('live calendar renders only real available slots and routes thanks only after a confirmed booking receipt',async()=>{
 const f=setup('lumen','api');await choose(f);assert.equal(f.node('slotGrid').children.length,1);await f.node('bookingForm').fire('submit');assert.equal(f.requests.length,2);const request=f.requests[1],url=new URL(request.url),body=JSON.parse(request.options.body);assert.equal(url.searchParams.get('client'),'lumen');assert.equal(body.locale,'en');assert.equal(body.customer.email,'visitor@example.test');assert.equal(f.completed.length,1);assert.equal(f.completed[0][3],'api');assert.equal(f.completed[0][4].eventId,'provider-event');assert(f.node('bookingContinue').disabled);
});
test('uncertain or rejected booking results never redirect or allow an immediate duplicate retry',async()=>{
 for(const receipt of [{ok:true},{ok:true,eventId:{}},{ok:false,eventId:'rejected'},new Error('timeout after server request')]){const f=setup('northline','api',receipt);await choose(f);await f.node('bookingForm').fire('submit');assert.equal(f.completed.length,0);assert(f.node('bookingContinue').disabled);assert.match(f.node('bookingResult').textContent,/before booking again/);await f.node('bookingForm').fire('submit');assert.equal(f.requests.length,2);}
});
test('restaurant calendar asks for guests, date and time rather than a menu dish and produces a table summary',async()=>{
 const f=setup('brasa');assert(f.node('main').innerHTML.includes('Guests'));assert.equal(f.node('timeHelp').textContent,'Choose a date first.');assert(!f.node('serviceList').innerHTML.includes('Crispy chicken'));f.node('tableGuests').value='4';f.node('tableGuests').fire('change');await choose(f);f.node('bookingContinue').fire('click');assert.equal(f.completed[0][2].type,'table');assert.equal(f.completed[0][2].party,4);assert.equal(f.requests.length,0);
});
test('sector booking labels do not inherit salon treatment terminology',()=>{for(const id of ['lumen','northline','brightmove']){const f=setup(id),markup=f.node('main').innerHTML;assert(!markup.includes('Treatment'));assert(markup.includes(id==='lumen'?'Appointment type':'Topic'));}});
