'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const registry=require('../client-config.js'),core=require('../core.js'),i18n=require('../i18n.js');
async function renderHome(lang,failReviews=false,withSnapshot=false){
 const config=structuredClone(registry.clients.ayden),nodes=new Map(),requests=[];
 if(!withSnapshot)delete config.google.snapshot;
 function node(id){if(nodes.has(id))return nodes.get(id);const element={id,dataset:{},hidden:false,textContent:'',addEventListener(){},append(){},insertAdjacentHTML(){},focus(){}};let markup='';Object.defineProperty(element,'innerHTML',{get:()=>markup,set:value=>{markup=value;for(const match of value.matchAll(/id="([^"]+)"/g))node(match[1]);}});nodes.set(id,element);return element;}
 node('main');
 const document={documentElement:{dataset:{page:'home'}},getElementById:id=>nodes.get(id)||null,querySelectorAll:()=>[],createElement:()=>node('temporary')};
 const window={Site:{config,lang,t:key=>i18n.localize(config.ui?.[key],lang)||i18n.translate(key,lang),l:v=>i18n.localize(v,lang),h:core.escape,link:p=>core.link(p,config.id,lang)},SiteCore:core,SalonCarousel:{mount(){return {destroy(){}};}},addEventListener(){}};
 const review={authorName:'Test author <unsafe>',profilePhotoUrl:'https://example.com/avatar.jpg',authorUri:'https://example.com/author',rating:4,text:'Een goede knipbeurt',language:'nl',originalText:'A good haircut',originalLanguage:'en',relativeTime:'yesterday',googleMapsUri:'https://www.google.com/maps/review'};
 const context={window,document,location:{origin:'http://localhost:4174',search:'?client=ayden&lang='+lang},URL,URLSearchParams,Intl,Date,AbortSignal,fetch:async url=>{requests.push(String(url));if(String(url).includes('/api/google-reviews'))return {ok:!failReviews,status:failReviews?503:200,json:async()=>({rating:4.7,total:47,url:config.business.mapsUrl,reviews:[review]})};return {ok:true,json:async()=>({photos:[{url:'https://example.com/salon.jpg',authorAttributions:[{displayName:'Photo author',uri:'https://example.com/photographer'}],googleMapsUri:config.business.mapsUrl}]})};}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../script.js'),'utf8'),context);
 await new Promise(resolve=>setImmediate(resolve));return {nodes,requests};
}
test('Recovered review feed renders real avatars, stars and attribution, with smart language selection',async()=>{const nl=await renderHome('nl'),en=await renderHome('en');const nlMarkup=nl.nodes.get('googleReviews').innerHTML,enMarkup=en.nodes.get('googleReviews').innerHTML;assert(nlMarkup.includes('Een goede knipbeurt'));assert(nlMarkup.includes('Originele beoordeling'));assert(enMarkup.includes('A good haircut'));assert(!enMarkup.includes('Original review'));assert(nlMarkup.includes('https://example.com/avatar.jpg'));assert(nlMarkup.includes('★★★★'));assert(nlMarkup.includes('Test author &lt;unsafe&gt;'));assert(nlMarkup.includes('https://example.com/author'));assert(nlMarkup.includes('data-carousel-next'));assert(nlMarkup.includes('data-carousel-toggle'));assert.equal(nl.nodes.get('googleAttribution').hidden,false);for(const url of nl.requests){const parsed=new URL(url);assert.equal(parsed.searchParams.get('client'),'ayden');assert.equal(parsed.searchParams.get('lang'),'nl');}});
test('Photos retain their author credits independently of review availability',async()=>{const {nodes}=await renderHome('en',true);assert(nodes.get('googleReviews').innerHTML.includes('awaiting activation'));assert(nodes.get('googleReviews').innerHTML.includes('retryGoogle'));assert(!nodes.get('googleReviews').innerHTML.includes('Test author'));const photos=nodes.get('googlePhotos').innerHTML;assert(photos.includes('https://example.com/salon.jpg'));assert(photos.includes('Photo author'));assert(photos.includes('https://example.com/photographer'));assert(photos.includes('data-carousel-track'));});
test('Ayden keeps dated real review excerpts visible when the unconfigured API is unavailable',async()=>{const {nodes}=await renderHome('en',true,true),markup=nodes.get('googleReviews').innerHTML;assert(markup.includes('Sebastiaan P'));assert(markup.includes('Very friendly and easy to make an appointment.'));assert(markup.includes('Translation for this concept'));assert(markup.includes('Google Maps ·'));assert(markup.includes('9 years ago'));assert(!markup.includes('9 jaar geleden'));assert(!markup.includes('Test author'));});
