'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {compileFunction}=require('../integration-loader.js');
const event=(client,method='GET',query={})=>({httpMethod:method,queryStringParameters:{client,...query},headers:{},body:'',rawUrl:'http://localhost:4174/api/bookings'});
test('Google source preserves avatars, critical reviews and smart translation without mixing businesses',async()=>{
 const oldFetch=global.fetch,oldEnv={...process.env};const translated=[];const places=[];
 process.env.GOOGLE_PLACES_API_KEY='unit-test-key';process.env.GOOGLE_TRANSLATE_API_KEY='unit-test-translate';process.env.GOOGLE_PLACE_ID='FF_PLACE_UNIT_TEST';
 const review=(name,rating,text,language,originalText,originalLanguage)=>({authorAttribution:{displayName:name,photoUri:'https://example.org/avatar.png',uri:'https://example.org/author'},rating,text:{text,languageCode:language},originalText:{text:originalText,languageCode:originalLanguage},relativePublishTimeDescription:'one month ago',publishTime:'2026-09-01T12:00:00Z',googleMapsUri:'https://maps.google.com/'});
 global.fetch=async(url,options)=>{if(String(url).includes('translation.googleapis.com')){translated.push(JSON.parse(options.body).q);return {ok:true,json:async()=>({data:{translations:[{translatedText:'Translated Spanish'}]}})};}places.push(String(url));return {ok:true,json:async()=>({rating:4.7,userRatingCount:47,googleMapsUri:'https://maps.google.com/',reviews:[review('Original EN',5,'Dutch text','nl','Original English','en'),review('Already EN',4,'Already English','en','Nederlands','nl'),review('Critical',2,'Texto','es','Texto','es')]})};};
 try{const fn=compileFunction('google-reviews');const ff=JSON.parse((await fn(event('ff','GET',{lang:'en'}))).body);assert.equal(ff.reviews[0].text,'Original English');assert.equal(ff.reviews[1].text,'Already English');assert.equal(ff.reviews[2].rating,2);assert.deepEqual(translated[0],['Texto']);assert.equal(ff.reviews[0].authorUri,'https://example.org/author');assert.equal(ff.reviews[0].profilePhotoUrl,'https://example.org/avatar.png');await fn(event('ayden','GET',{lang:'en'}));assert.ok(places.some(url=>url.includes('FF_PLACE_UNIT_TEST')));assert.ok(places.some(url=>url.includes('ChIJWQ2FSAq3xUcRmbPxHN8NGL8')));assert.equal((await fn(event('constructor','GET',{lang:'en'}))).statusCode,400);}finally{global.fetch=oldFetch;for(const name of Object.keys(process.env))if(!(name in oldEnv))delete process.env[name];Object.assign(process.env,oldEnv);}
});
test('FF calendar credentials cannot create a booking for unconfigured Ayden',async()=>{
 const oldEnv={...process.env};process.env.GOOGLE_CALENDAR_ID='FF_ONLY';process.env.GOOGLE_CLIENT_EMAIL='unit@example.org';process.env.GOOGLE_PRIVATE_KEY='not-a-real-key';delete process.env.ACTIVE_CALENDAR_CLIENT_ID;
 try{const fn=compileFunction('bookings');const result=await fn(event('ayden','POST'));assert.equal(result.statusCode,503);assert.match(result.body,/calendar_not_configured_for_business/);}finally{for(const name of Object.keys(process.env))if(!(name in oldEnv))delete process.env[name];Object.assign(process.env,oldEnv);}
});
test('restored FF booking checks availability, creates the event and emails its client-specific cancellation link',async()=>{
 const oldEnv={...process.env};Object.assign(process.env,{ACTIVE_CALENDAR_CLIENT_ID:'ff',GOOGLE_CALENDAR_ID:'FF_UNIT',GOOGLE_CLIENT_EMAIL:'unit@example.org',GOOGLE_PRIVATE_KEY:'unit-key',RESEND_API_KEY:'unit-email',BOOKING_FROM_EMAIL:'unit@example.org',BOOKING_ADMIN_EMAIL:'admin@example.org'});
 const calls=[];const calendar={freebusy:{query:async()=>{calls.push('availability');return {data:{calendars:{FF_UNIT:{busy:[]}}}};}},events:{insert:async request=>{calls.push(request);return {data:{id:'unit-event'}};},delete:async()=>calls.push('delete')}};
 const google={auth:{JWT:class{}},calendar:()=>calendar};const emails=[];class Resend{constructor(){this.emails={send:async request=>{emails.push(request);return {error:null,data:{id:'unit-email'}};}};}}
 try{const fn=compileFunction('bookings',{googleapis:{google},resend:{Resend}});const date=new Date();do{date.setDate(date.getDate()+1);}while(date.getDay()===0||date.getDay()===6);const dateKey=[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');const request=event('ff','POST');request.body=JSON.stringify({serviceId:'oil',date:dateKey,time:'08:00',locale:'en-GB',customer:{name:'Unit Test',email:'customer@example.org',phone:''}});const response=await fn(request);assert.equal(response.statusCode,200,response.body);assert.equal(JSON.parse(response.body).eventId,'unit-event');assert.equal(calls[0],'availability');assert.equal(calls[1].calendarId,'FF_UNIT');assert.equal(emails[0].to,'customer@example.org');assert.match(emails[0].text,/client=ff/);assert.ok(calls[1].requestBody.extendedProperties.private.cancellationToken);}finally{for(const name of Object.keys(process.env))if(!(name in oldEnv))delete process.env[name];Object.assign(process.env,oldEnv);}
});
